
import { Request, Response } from 'express';
import { validationResult } from 'express-validator';
import { v2 as cloudinary, UploadApiResponse } from 'cloudinary';
import Ad from '../models/Ad';

// Extend the Express Request type to include our custom property
declare global {
  namespace Express {
      interface Request {
            cloudinaryResult?: UploadApiResponse;
                }
                  }
                  }
                  
                  const CATEGORIES = ['Immobilier', 'Véhicules', 'Maison & Jardin', 'Électronique', 'Loisirs', 'Mode', 'Autres'];
                  
                  // @desc    Affiche toutes les annonces avec pagination et filtres
                  export const getAds = async (req: Request, res: Response) => {
                      try {
                              const page = parseInt(req.query.page as string) || 1;
                                      const limit = 8;
                                              const category = req.query.category as string || '';
                                                      const query: any = { status: 'approved' }; // CORRECTION: Affiche seulement les annonces approuvées
                                                              if (category) {
                                                                          query.category = category;
                                                                                  }
                                                                                  
                                                                                          const result = await Ad.paginate(query, { page, limit, sort: { createdAt: -1 }, populate: 'author' });
                                                                                          
                                                                                                  res.render('ads/index', {
                                                                                                              title: 'Toutes les annonces',
                                                                                                                          description: "Parcourez des milliers de petites annonces au Sénégal. Trouvez des voitures, des maisons, des emplois et plus encore sur AfrikMarket.",
                                                                                                                                      keywords: "petites annonces, Sénégal, immobilier, voitures, emploi, AfrikMarket",
                                                                                                                                                  ads: result.docs,
                                                                                                                                                              current: result.page,
                                                                                                                                                                          totalPages: result.totalPages,
                                                                                                                                                                                      category: category,
                                                                                                                                                                                                  categories: CATEGORIES
                                                                                                                                                                                                          });
                                                                                                                                                                                                              } catch (err: any) {
                                                                                                                                                                                                                      console.error(err.message);
                                                                                                                                                                                                                              req.flash('error_msg', 'Erreur lors de la récupération des annonces.');
                                                                                                                                                                                                                                      res.redirect('/');
                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                          // @desc    Affiche une seule annonce
                                                                                                                                                                                                                                          export const getAd = async (req: Request, res: Response) => {
                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                      const ad = await Ad.findById(req.params.id).populate('author');
                                                                                                                                                                                                                                                              if (!ad) {
                                                                                                                                                                                                                                                                          req.flash('error_msg', 'Annonce non trouvée.');
                                                                                                                                                                                                                                                                                      return res.redirect('/ads');
                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                      const isAuthor = req.user && ad.author && (ad.author as any)._id.toString() === req.user._id.toString();
                                                                                                                                                                                                                                                                                                              const isAdmin = req.user && req.user.role === 'admin';
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                      // Prepare meta description (truncate for best SEO practice)
                                                                                                                                                                                                                                                                                                                              const metaDescription = ad.description.length > 155 ? ad.description.substring(0, 152) + '...' : ad.description;
                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                      res.render('ads/show', {
                                                                                                                                                                                                                                                                                                                                                  title: ad.title,
                                                                                                                                                                                                                                                                                                                                                              ad,
                                                                                                                                                                                                                                                                                                                                                                          isAuthor,
                                                                                                                                                                                                                                                                                                                                                                                      isAdmin,
                                                                                                                                                                                                                                                                                                                                                                                                  // SEO Meta Tags
                                                                                                                                                                                                                                                                                                                                                                                                              description: metaDescription.replace(/\r\n|\n|\r/gm, ' '), // Remove line breaks for meta tag
                                                                                                                                                                                                                                                                                                                                                                                                                          imageUrl: ad.imageUrl,
                                                                                                                                                                                                                                                                                                                                                                                                                                      keywords: `${ad.title}, ${ad.category}, AfrikMarket`
                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                  } catch (err: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.error(err.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  res.redirect('/ads');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // @desc    Affiche le formulaire pour créer une nouvelle annonce
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export const getNewAdForm = (req: Request, res: Response) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          res.render('ads/new', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   title: 'Créer une annonce', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            categories: CATEGORIES, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     errors: [], 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              oldInput: {}, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       description: "Publiez gratuitement votre annonce sur AfrikMarket et touchez des milliers d'acheteurs potentiels au Sénégal.", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                keywords: "vendre, annonce gratuite, Sénégal, AfrikMarket" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // @desc    Gère la création d'une nouvelle annonce
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export const createAd = async (req: Request, res: Response) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const errors = validationResult(req);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!errors.isEmpty()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return res.status(400).render('ads/new', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                title: 'Créer une annonce', categories: CATEGORIES, errors: errors.array(), oldInput: req.body
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const { title, description, price, category } = req.body;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const newAd = new Ad({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            title, description, price, category, author: req.user
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // The uploadToCloudinary middleware has run, and the result is on req.cloudinaryResult
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (req.cloudinaryResult) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                newAd.imageUrl = req.cloudinaryResult.secure_url;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            newAd.imageFilename = req.cloudinaryResult.public_id; // public_id is the identifier for deletion
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await newAd.save();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    req.flash('success_msg', 'Annonce créée avec succès ! Votre annonce est en attente d\'approbation par un administrateur.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.redirect('/ads');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (err: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.error(err.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                req.flash('error_msg', 'Erreur lors de la création de l\'annonce.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.redirect('/ads/new');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // @desc    Affiche le formulaire pour éditer une annonce
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export const getEditAdForm = async (req: Request, res: Response) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const ad = await Ad.findById(req.params.id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!ad) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            req.flash('error_msg', 'Annonce non trouvée.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return res.redirect('/ads');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.render('ads/edit', { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    title: 'Modifier l\'annonce', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ad, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            categories: CATEGORIES, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        errors: [], 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   oldInput: ad,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                description: `Modifiez votre annonce: ${ad.title}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            keywords: `modifier, édition, ${ad.category}, ${ad.title}`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (err: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error(err.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.redirect('/ads');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
// @desc    Gère la mise à jour d'une annonce
export const updateAd = async (req: Request, res: Response) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
        const adData = { ...req.body, _id: req.params.id };
        return res.status(400).render('ads/edit', {
            title: 'Modifier l\'annonce', ad: adData, categories: CATEGORIES, errors: errors.array(), oldInput: req.body
        });
    }

    try {
        const ad = await Ad.findById(req.params.id);
        if (!ad) {
            req.flash('error_msg', 'Annonce non trouvée');
            return res.redirect('/ads');
        }

        // Mettre à jour les champs de l'annonce
        ad.title = req.body.title;
        ad.description = req.body.description;
        ad.price = req.body.price;
        ad.category = req.body.category;
        ad.status = 'pending'; // Repasse le statut à "en attente"

        // Vérifier si un nouveau fichier a été téléchargé
        if (req.cloudinaryResult) {
            // Supprimer l'ancienne image si elle existe
            if (ad.imageFilename) {
                await cloudinary.uploader.destroy(ad.imageFilename);
            }
            // Enregistrer les détails de la nouvelle image
            ad.imageUrl = req.cloudinaryResult.secure_url;
            ad.imageFilename = req.cloudinaryResult.public_id;
        }

        await ad.save();

        req.flash('success_msg', 'Annonce mise à jour. Elle est maintenant en attente d\'approbation.');
        res.redirect('/profile'); // Rediriger vers le profil

    } catch (err: any) {
        console.error(err.message);
        req.flash('error_msg', 'Erreur lors de la mise à jour.');
        res.redirect(`/ads/${req.params.id}/edit`);
    }
};


// @desc    Supprime une annonce
export const deleteAd = async (req: Request, res: Response) => {
    try {
        const ad = await Ad.findById(req.params.id);
        if (!ad) {
            req.flash('error_msg', 'Annonce non trouvée.');
            return res.redirect('/ads');
        }
        if (ad.imageFilename) {
            // This uses the public_id to delete the image from Cloudinary
            await cloudinary.uploader.destroy(ad.imageFilename);
        }
        await Ad.deleteOne({ _id: req.params.id });
        req.flash('success_msg', 'Annonce supprimée avec succès.');
        res.redirect('/ads');
    } catch (err: any) {
        console.error(err.message);
        req.flash('error_msg', 'Erreur lors de la suppression.');
        res.redirect('/ads');
    }
};
